# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon = false

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
loader_version=0.18.6
loom_version=1.14-SNAPSHOT

# Fabric API
fabric_version=0.116.7+1.21.1

# 1.21.1 compatibility baseline
sodium_version=mc1.21.1-0.6.13-fabric
lithium_version=mc1.21.1-0.15.3-fabric
nvidium_version=0.3.1
modmenu_version=11.0.4
iris_version=1.8.8+1.21.1-fabric
sodium_extra_version=mc1.21.1-0.6.0+fabric
chunky_version=RVFHfo1D
fabric_permissions_api_version=0.3.1
vivecraft_version=1.21.1-1.3.7-fabric
distanthorizons_version=2.4.5-b-1.21.1
lwjgl_version=3.3.3


# Mod Properties
mod_version = 0.2.13-alpha
maven_group = me.cortex
archives_base_name = voxy
